### ISSUE TITLE
Errors on examples - iris example

### ISSUE THREAD

**Issue by andrewcz** [cgnorthcutt/confidentlearning#1]
Hi!
Really like the package just getting some errors on the example -

![screenshot_2018-09-25_21-56-48](https://user-images.githubusercontent.com/2296335/46012881-e70e2680-c10d-11e8-8e3f-3c534ad933c2.png)

Hope you can assist.
Best,
Andrew

**Comment by andrewcz** [comment]
![screenshot_2018-09-25_22-01-44](https://user-images.githubusercontent.com/2296335/46013082-7ddae300-c10e-11e8-9e05-b799d4766b02.png)

the example in jupyter notebook.
best,
Andrew

**Comment by cgnorthcutt** [comment]
@andrewcz Hey thanks for this comment. I just saw this (there are no email notifications for comments). I'll look into a fix tomorrow and update.

**Comment by andrewcz** [comment]
Amazing thank you @cgnorthcutt Really like the package and algorithms.
Plan to build on it.
Have an amazing day and weekend.
Many thanks,
Best,
Andrew

**Comment by cgnorthcutt** [comment]
@andrewcz I have fixed that particular issue. It stems from a change to push the hyper-parameters into the intialization of the RankPruning() class objects instead of in the .fit() function. This is how most libraries work and lets us more easily do hyper-parameter optimization.

By the way if you plan on branching off of this package, you'll like want to wait a month or so. I'm doing a full overhaul over the next month in preparation for a long overdue publication. The package will shift to a more professional state.

Get ready for the future when learning with noisy labels is as easy as a few lines of code with this package!
